### ISSUE TITLE
Threshold evaluation backwards for complete and single linkages?

### ISSUE THREAD

**Issue by castillohair** [jaimicore/matrix-clustering_stand-alone#5]
Thank you for the very useful software. In funcion `nodes.summary.stats` in `R/Tree_partition_utils.R` the decision on whether to split cluster nodes is made. For this, a set of summary statistics for each node is calculated based on a summary function that is selected at the beginning of the file based on the selected linkage :

```R
## Return the function that will be applied: mean (average linkage), min (single linkage),
## or max (complete linkage)
function.to.apply <- function(parameters = NULL){
  
  switch(params.list$linkage_method,
         average  = mean,
         single   = min,
         complete = max)
}
```

However, the statistics are calculated in terms of correlations and not distances. Therefore, for the "complete" linkage using the maximum correlation means the minimum distance is being used, and the other way around for the "single" linkage. I think this should be backwards. The practical consequence is that with "complete" linkage I'm seeing that the resulting clusters contain very obvious subclusters that are not split no matter how much I change the thresholds.

Therefore, I would propose changing these lines as follows:

```R
## Return the function that will be applied: mean (average linkage), min (single linkage),
## or max (complete linkage)
function.to.apply <- function(parameters = NULL){
  
  switch(params.list$linkage_method,
         average  = mean,
         single   = max,
         complete = min)
}
```

**Comment by jaimicore** [comment]
Hi,

thanks for the correction.

This change is now added in the commit [f20166a](https://github.com/jaimicore/matrix-clustering_stand-alone/commit/f20166a85c6690930dbf19bb469cf3dd1fa4cfff).
