### ISSUE TITLE
Code using both cor and Ncor to split clusters

### ISSUE THREAD

**Issue by castillohair** [jaimicore/matrix-clustering_stand-alone#6]
Thank you for the very useful software. Line 29 of file `Tree_partition_utils.R` suggests that both cor and Ncor are being used to decide whether to split a cluster, even though there is a `--comparison_metric` parameter whose documentation implies only one or the other is used. Is this correct? Is there a rationale for this behavior?

**Comment by jaimicore** [comment]
Hi ,

The motifs are compared using two metrics, pearson correlation (*cor*) and width-normalized pearson correlation (*Ncor*).

The hierarchical tree is computed using one of these metrics (default : *Ncor*), but when we create the progressive alignment and to decide if we add an extra motif or we split a branch, we compute the average (or min/max depending on the linkage type selected by the user) of the *Ncor* and *cor* values.

This rationale is based on a grid search evaluation we made in the matrix-clustering paper (see the supplementary notes), we observed that a threshold in these two metrics provided better results than using a single metric.
